### ISSUE TITLE
Can't configure basic auth via config

### ISSUE THREAD

**Issue by chiiya** [CodeDredd/laravel-soap#103]
When building a client via config (`Soap::buildClient('frontend')`) with the `with_basic_auth` option configured, the `SoapClient::withBasicAuth()` method throws the following error:

```
Argument 1 passed to CodeDredd\\Soap\\SoapClient::withBasicAuth() must be of the type string, array given
```

Example config:

```php
'clients' => [
    'frontend' => [
        'base_wsdl' => 'https://example.org//soap?wsdl',
        'with_basic_auth' => [
            'username' => 'xyz',
            'password' => 'xyz',
        ],
    ],
],
```

This is due to the way array config options are handled by the `SoapClient::byConfig()` method:

```php
} elseif (is_array($setupItemConfig)) {
    $this->{Str::camel($setupItem)}($this->arrayKeysToCamel($setupItemConfig));
}
```

That will call `SoapClient::withBasicAuth()` with an array as the only parameter (`['username' => 'xyz', 'password' => 'xyz']`), whereas the method signature expects two string parameters (`string $username, string $password`).

The `SoapClient::withBasicAuth()` method should probably be adapted to accept an array configuration as well, similar to how Laravel itself handles some of its methods (by checking if the first parameter is an array or a string). I can create a pull request if you're happy with that solution.

**Comment by CodeDredd** [comment]
You're right.

**Comment by chiiya** [comment]
Another thing I noticed: when I specify `with_options` in the config file, the options themselves are camelcased before being passed to the soap constructor, so e.g. `cache_wsdl` becomes `cacheWsdl` which of course throws an error.

**Comment by CodeDredd** [comment]
Thanks for noticing. I really appricate it if you open an PR. Otherwise i will of course try to tackle it at some point.
Btw merged your changes already in master also and made new releases

**Comment by CodeDredd** [comment]
Closed with #105

**Comment by chiiya** [comment]
Yea, sure. I do have a question though: why is the `$this->arrayKeysToCamel($setupItemConfig)` part necessary at all? Is it just for the `WsseMiddleware`? If so, it would probably be better to handle the camelcasing there :thinking:

**Comment by CodeDredd** [comment]
@chiiya No its not just for that. But yeah it was the main reason introducing it. I just wanted a consistent config without rewriting all the code i use from phpro. The right way to do it would be of course in the files do i dont need that function.
