### ISSUE TITLE
Install Issue on Laravel 8.X

### ISSUE THREAD

**Issue by marweb** [CodeDredd/laravel-soap#104]
Laravel 8 use guzzle ^7.0, but  php-http/guzzle6-adapter require guzzlehttp/guzzle ^6.0.

Laravel 8 install error:

  **Problem 1**
    - Installation request for guzzlehttp/guzzle (locked at 7.2.0, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.2.0].
    - php-http/guzzle6-adapter 2.x-dev requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - php-http/guzzle6-adapter v2.0.0 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - php-http/guzzle6-adapter v2.0.1 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Conclusion: don't install codedredd/laravel-soap v1.3.1|install guzzlehttp/guzzle 6.5.x-dev
    - Conclusion: don't install guzzlehttp/guzzle 6.5.x-dev
    - codedredd/laravel-soap v1.3.0 requires php-http/guzzle6-adapter ^2.0 -> satisfiable by php-http/guzzle6-adapter[2.x-dev, v2.0.0, v2.0.1].

**Comment by CodeDredd** [comment]
Hey. U need to install version 2 for Laravel 8. Version 2 is still a prerelease. I make now a release maybe so it doesnt come to that problem. Seems i do my breaking changes in version 3 :-)

**Comment by CodeDredd** [comment]
Closed with new release
