### ISSUE TITLE
Content-Type being overwritten

### ISSUE THREAD

**Issue by ryanmitchell** [CodeDredd/laravel-soap#115]
First of all thanks for this library - its very useful for a project I'm working through.

I have an service that requires a specific content-type value (application/soap+xml; charset=utf-8), however when I use this class and pass content-type using withHeaders() the content-type is always being set as text/xml; charset="utf-8". Is it possible to override this somehow - I've tried a few different approaches and have come up with nothing...

**Comment by CodeDredd** [comment]
Thanks. I am going to try it out locally. First i need a working example to see what the problem is.

**Comment by ryanmitchell** [comment]
Sure, so what I'm doing is:


```
        $client = Soap::withHeaders([
                'Content-Type' => 'application/soap+xml; charset=utf-8',
            ])
            ->baseWsdl($baseUrl.'/PosterUpload2/PosterUpload.svc?wsdl')
            ->withWsse([
                'userTokenName' => getenv('SOAP_USER'),
                'userTokenPassword' => getenv('SOAP_PASSWORD'),
            ])
            ->withWsa()
            ->withOptions([
                'trace' => true,
                'exceptions' => false,
            ]);
            
            $response = $client->CreateManifest(['Body' => $xml]);
```

**Comment by CodeDredd** [comment]
@ryanmitchell After some tackeling i fixed the problem. Making PR and release. Please also remember that you also still have an mistake. You have to set it to:
`application/soap+xml; charset="utf-8"`

**Comment by ryanmitchell** [comment]
This looks perfect. thank you so much!

**Comment by CodeDredd** [comment]
@ryanmitchell One question...i just thought again about your problem and have seen that your header is the standard for soap version 1.2. So is it the case that you just needed to define th SOAP version to 1.2 ?

**Comment by ryanmitchell** [comment]
Possibly... to be honest the documentation for the end point isn't wonderful. How do you specify the version?

**Comment by CodeDredd** [comment]
@ryanmitchell 
````php
        $client = Soap::baseWsdl('url?wsdl')
                      ->withOptions([
                          'soap_version' => SOAP_1_2
                      ]);
````
