### ISSUE TITLE
SoapHeader

### ISSUE THREAD

**Issue by serdud** [CodeDredd/laravel-soap#125]
Hi.
How I can set SoapHeader? It seems withHeaders method isn't what I need. Thanks.
https://prnt.sc/11bvcia

**Comment by CodeDredd** [comment]
@serdud DHL uses its own authentication process. You can write a middleware for it.
For start I've done a prototype of it. Feel free to test it and extend it.

**Comment by serdud** [comment]
Thank you, it works. But you make a typo in header element name: must be "cis:Authentification" instead of "cis:Authentication".

**Comment by CodeDredd** [comment]
Thanks for testing. Making an release.
I should extend the docs...or if you have time i would appreciate it ^^.
