### ISSUE TITLE
Transfer-Encoding : Chunked Issue

### ISSUE THREAD

**Issue by erguntech** [CodeDredd/laravel-soap#135]
Hi CodeDredd;

I can get data from most of them. Only one function is returning a pdf file as byte format. When i try to read the response, i only got a blank data. When i use The SoapUI, it returns me back the pdf file. But in PHP it's not working somehow.

For example, this code returns data without problem.
```
public function getSupplyCarryTypes(Request $request)
{
    $response = Soap::baseWsdl('https://servis.turkiye.gov.tr/services/g2g/kdgm/test/uetdsesya?wsdl')
        ->withBasicAuth('999999', '999999testtest')
        ->withOptions([
            'trace' => false,
            'encoding' => 'UTF-8',
            'cache_wsdl' => WSDL_CACHE_NONE,
        ])
        ->call('paramTehlikeliMaddeTasimaSekli',array(
            'wsuser' => array('kullaniciAdi' => '999999', 'sifre' => '999999testtest')));

    dd($response['return']['tehlikeliMaddeTasimaSekliListesi']);
}
```

But when i try this one, it returns null. It normally returns a PDF file as bytes. At least it's working well in SoapUI.After cheking the raw codes in SoapUI, i saw that the only difference is "Transfer Encoding : chunked".

```
public function getVoyageReport() // Not Working
{
    $response = Soap::baseWsdl('https://servis.turkiye.gov.tr/services/g2g/kdgm/test/uetdsesya?wsdl')
        ->withBasicAuth('999999', '999999testtest')
        ->withOptions([
            'trace' => false,
            'encoding' => 'UTF-8',
            'cache_wsdl' => WSDL_CACHE_NONE,
        ])
        ->call('seferRaporuV3', array(
            'wsuser' => array('kullaniciAdi' => '999999', 'sifre' => '999999testtest'),
            'seferId' => '21042300246027'));

    return $response->body();
}
```

Am i missing something? I would be really happy, if you take a look...
Thanks...

**Comment by CodeDredd** [comment]
@erguntech Hey. Sorry for answering so late. Last weeks i had a lot of work.
So the problem you describe is not really solved. I hope i come this week to tackle all the issues.
