### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by giraz82** [CodeDredd/laravel-soap#141]
Hi, and thank you for this great library.
I have this issue:
```
CodeDredd\Soap\Exceptions\SoapException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://webservicestest.vwgroup.it/proxy/WSDatiVeicoli.asmx

/var/www/html/vendor/codedredd/laravel-soap/src/Exceptions/SoapException.php:17
/var/www/html/vendor/codedredd/laravel-soap/src/SoapClient.php:368
...

Caused by
GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for [...]
```

In a standard approach, using php SoapClient I'm able to connect to this SOAP service adding this options:
```php
$options = [
    'stream_context' => stream_context_create(
        [
            'ssl' => [
                'verify_peer' => false,
                'verify_peer_name' => false,
                'allow_self_signed' => true,
            ],
        ]
    ),
];
```
But it seems that this is not working with your implementation that uses Guzzle under the hood.
If I tweak Guzzle client default options putting `false` on `verify`, then it works:
```php
$defaults = [
    'allow_redirects' => RedirectMiddleware::$defaultSettings,
    'http_errors' => true,
    'decode_content' => true,
    'verify' => false,
    'cookies' => false,
    'idn_conversion' => false,
];
```
Is there a way to pass some option to Guzzle from CodeDredd Soap facade?

I don't have any control on the server side.

Thank you

**Comment by CodeDredd** [comment]
@giraz82 Thanks and hello
You can set the guzzle config like that:
````php
        $client = Soap::withHandlerOptions([
            'allow_redirects' => RedirectMiddleware::$defaultSettings,
            'http_errors' => true,
            'decode_content' => true,
            'verify' => false,
            'cookies' => false,
            'idn_conversion' => false,
        ])->baseWsdl('https://laravel-soap.wsdl');
        $response = $client->call('Get_User');
````

i also saw that i had a typo in the factory class. 🥴  Changed it and making a new release.

Tell me if it works. Thanks!

**Comment by giraz82** [comment]
@CodeDredd yep, your hint was correct, in that way I can pass specific options to Guzzle, thank you!

Unfortunately it was very late when I was dealing with that code and I didn't realise that `withHeaders` function add http headers, and not soap headers to soap request envelop.
What I would need in the xml request is
```xml
<soap:Header>
  <AuthHeader xmlns="http://www.sapledomain.com/">
    <Username>user</Username>
    <Password>password</Password>
  </AuthHeader>
</soap:Header>
```
But this is a different problem form the one I opened the issue for.

**Comment by CodeDredd** [comment]
@giraz82 Well for this usecase i use `middlewares`. Take a look at the DHL Middleware.
Feel free to make a PR if it is a middleware for a thrid party service.
If you need help to make it just tell me and i make this custom header ;-)

**Comment by giraz82** [comment]
Thank you for the hint, I will have a look for sure
