### ISSUE TITLE
Laravel 8 in not install

### ISSUE THREAD

**Issue by vinchamp** [CodeDredd/laravel-soap#159]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - codedredd/laravel-soap[v1.5.0, ..., v1.5.1] require illuminate/support ^5.6 || ^6.0 || ^7.0 -> found illuminate/support[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^8.56).
    - Root composer.json requires codedredd/laravel-soap ^1.5 -> satisfiable by codedredd/laravel-soap[v1.5.0, v1.5.1].

**Comment by micobarac** [comment]
@vinchamp, please run `composer require codedredd/laravel-soap:v2.0.0-rc.1` for 8.0.

**Comment by vinayzoneone** [comment]
> @vinchamp, please run `composer require codedredd/laravel-soap:v2.0.0-rc.1` for 8.0.

Thnak you , It is working. :)

**Comment by Whizboy-Arnold** [comment]
phewx

> > @vinchamp, please run `composer require codedredd/laravel-soap:v2.0.0-rc.1` for 8.0.
> 
> Thnak you , It is working. :)

confirmed

**Comment by veerababuyarramalla** [comment]
@micobarac ,I need for laravel 7.

**Comment by CodeDredd** [comment]
@veerababuyarramalla You need `composer require codedredd/laravel-soap:v1.5.1` for 7.0
