### ISSUE TITLE
soap url instead of baseWsdl

### ISSUE THREAD

**Issue by yientau** [CodeDredd/laravel-soap#171]
Hi, is there any way I can call an endpoint without getting the baseWsdl? The reason I asked is, the url that my soap client does not return the wsdl. I have the wsdl file though. Can I set the wsdl file locally and access the soap client with an url? The method baseWsdl expect a wsdl file to be returned. Please advise.

**Comment by carlosolivas** [comment]
Hi @yientau,

I have the same issue, did you manage to solve this?

Any help is much appreciated
