### ISSUE TITLE
Call to undefined method GuzzleHttp\Psr7\Response::succesful()

### ISSUE THREAD

**Issue by odin88** [CodeDredd/laravel-soap#176]
Using laravel 7.

Maybe because of this ? https://stackoverflow.com/a/45714340

**Comment by CodeDredd** [comment]
Hey @odin88 ,

sry for the late answer. Family & Work. ^^. Which version were you using with this package?

**Comment by CodeDredd** [comment]
Hey @odin88 ,

thanks for the answer. Do you have also a stacktrace? Would help much to reproduce the error and find the reason.
Thank you!

**Comment by odin88** [comment]
I have confirmed that it is an instance of "CodeDredd\Soap\Client\Response"
<img width="968" alt="image" src="https://user-images.githubusercontent.com/680300/153769981-2089b0e4-36e8-4bf4-a105-204a0ceec6ad.png">

```
 
        $response->succesful();
```

**Comment by CodeDredd** [comment]
@odin88 find your reason ^^ .... you got a typo. you are using `succesful` instead of `successful`. You missed an s. 😉
