### ISSUE TITLE
Hi everyone! i have a following question: how to set a timeout to soap call???

### ISSUE THREAD

**Issue by sramirezse** [CodeDredd/laravel-soap#210]
### Discussed in https://github.com/CodeDredd/laravel-soap/discussions/209

<div type='discussions-op-text'>

<sup>Originally posted by **sramirezse** March 24, 2022</sup>
I tried to use withOptions(['connection_timeout' and 'default_socket_timeout' but the response takes much longer and does not throw an error, this is my code:

`try{

            $responseGetOrder = Soap::baseWsdl($this->url)->withOptions([
                'connection_timeout' => 30,
                'default_socket_timeout' => 30,
            ])->getOrder([
                'user' => $this->user,
                'operator' => $this->operator,
                'idProduct' => 'RMP100',
                'numberAccount' => 5511111160,
                // 'numberAccount' => 3334441122,
                // 'numberAccount' => 5511111130,
                'clientFolio' => $serviceAttempt->id,
            ]);
            $responseGetOrderBody = $responseGetOrder->json();
            return $responseGetOrderBody;
        }catch(\Exception $e){
           dd($e);
        }`
this is the time it takes to respond, sorry my bad english
![imagen](https://user-images.githubusercontent.com/49218071/159870837-eb4d23c3-4666-44a0-88a1-98048a2fb178.png)
</div>

**Comment by CodeDredd** [comment]
@sramirezse heyho

if i find time i try to investigate that a bit. It't diffuclt to pinpoint the reason here. I also don't know yet how to find out where the reason can be... *thinking mode on* 🤔

**Comment by veewee** [comment]
The reason here is because you use guzzle and not PHP's built-in SoapClient.
You'll need to pass timeout configs to guzzle instead.

(However : for wsdl fetching, the timeouts are most likely still being used)

**Comment by CodeDredd** [comment]
passing options to guzzle `works with
````php 
Soap::withGuzzleClientOptions([
...
])
````
i also included there performance stats so you can check the request & response time which is easy debuggable with spatie ray.

@veewee is one the SOAP Gurus so listen to him ;-)

**Comment by sramirezse** [comment]
Hi!, i solved the problem using php soap client, thanks for every one!

**Comment by sramirezse** [comment]
Hii @CodeDredd , thank you very much for answering my question
