### ISSUE TITLE
Proxy settings do not reach Guzzle

### ISSUE THREAD

**Issue by molbal** [CodeDredd/laravel-soap#219]
### Reproduction

Setting the proxy settings using 
```php
$soap = Soap::baseWsdl($wsdl)->withOptions([
                    'proxy_host' =>'...',
                    'proxy_port' => '..',
                    'proxy_login' => "",
                    'proxy_password' => "",
                ]);

```

and then making a call with 
```php
$soap->Call('Ping', []);
```
does not use the proxy.

If I manually edit the `GuzzleHttp\Handler\CurlHandler` class to burn in the proxy, then the proxy server is used. (Obv., this workaround is not suitable outside dev env)

```php

    public function __invoke(RequestInterface $request, array $options): PromiseInterface
    {
        if (isset($options['delay'])) {
            \usleep($options['delay'] * 1000);
        }

        // Dirty dirty hack!!!!
        $options['proxy'] = config('soap.proxy');

        $easy = $this->factory->create($request, $options);
        \curl_exec($easy->handle);
        $easy->errno = \curl_errno($easy->handle);

        return CurlFactory::finish($this, $easy, $this->factory);
    }
```

### Expected behavior

The library directly tries to call the SOAP host, though the proxy server.

### Actual behavior

The library directly tries to call the SOAP host, without using the proxy server.

### Additional information

![image](https://user-images.githubusercontent.com/5754480/165845440-5a10593c-b227-490e-94b6-bccd0b328c72.png)

Thank you for your assistance

**Comment by CodeDredd** [comment]
Which version are you using? If your using the new one you need to use `withGuzzleOptions` to pass options to guzzle

**Comment by molbal** [comment]
I missed that, it works that way. Thanks
