### ISSUE TITLE
Using Wsa 2005

### ISSUE THREAD

**Issue by bretto36** [CodeDredd/laravel-soap#220]
We have a SOAP implementation that uses WSA 2005. Is it possible to add a method to add WSA2005 support from php-soap

->withWsa2005()

**Comment by bretto36** [comment]
We are curently using v2 because v3 requires laravel 9 and we haven't quite got to that yet

**Comment by CodeDredd** [comment]
@bretto36 yeah should be possible. i wonder if the wsa library which v2 uses under the hood doesn't have support for that. Maybe i just need to add a option....trying to find time for that ^^...

**Comment by bretto36** [comment]
@CodeDredd  

See #225

**Comment by bretto36** [comment]
I didn't solve it for v2, but it's added for v3 in the PR. We will attempt to get to Laravel 9 so we don't have to worry about v3 anymore

Thanks for the package

**Comment by CodeDredd** [comment]
@bretto36 your welcome. Thanks for the PR. Merged it.

**Comment by CodeDredd** [comment]
closed by #225
