### ISSUE TITLE
Problem installation with Laravel 8.8 - failed 

### ISSUE THREAD

**Issue by Vasiliy-Makogon** [CodeDredd/laravel-soap#224]
Problem 1
    - codedredd/laravel-soap[v1.5.0, ..., v1.5.1] require illuminate/support ^5.6 || ^6.0 || ^7.0 -> found illuminate/support[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires codedredd/laravel-soap ^1.5 -> satisfiable by codedredd/laravel-soap[v1.5.0, v1.5.1].

**Comment by CodeDredd** [comment]
@Vasiliy-Makogon Use v2 for laravel 8 please as mentioned in the readme. v1 is not compatible with laravel 8.

**Comment by CodeDredd** [comment]
@Vasiliy-Makogon i released a final v2 so its no longer in rc state. So it should be finally easy to install the right version.
