### ISSUE TITLE
Wrong Version - Version Mismatch laravel Soap vs PHP SoapClient

### ISSUE THREAD

**Issue by cladico** [CodeDredd/laravel-soap#228]
Bellow code with laravel-soap:
```
$client = Soap::baseWsdl($url)
->withOptions([
    'location' => $url,
    'soap_version' => SOAP_1_1,
    'local_cert' => storage_path('app/local_cert.pem'),
    'trace' => true,
    'keep_alive' => true,
    'exceptions' => true,
    'cache_wsdl'=> WSDL_CACHE_NONE,
]);    

$response = $client->call('retrieveInfo', [
  'username' => 'admin',
  'password' => 'awesome',
]);
```
Returns: Wrong Version

Bellow code with php soapClient
```
$client = new \SoapClient($url, array(
  'location' => $url,
  'soap_version' => SOAP_1_1,
  'local_cert' => storage_path('app/local_cert.pem'),
  'trace' => true,
  'keep_alive' => true,
  'exceptions' => true,
  'cache_wsdl'=> WSDL_CACHE_NONE,
));

$response = $client->__soapCall("retrieveInfo", array([
  'username' => 'admin',
  'password' => 'awesome',
]));
```
Returns: Success and works

Please tell what tests to do so i can give more details, sadly i cannot attach the Wsdl.
Thank you!

**Comment by cladico** [comment]
> Hello @cladico , thanks for posting this bug and sry for late answer. Which laravel-soap version are you using? Which php version? And which laravel version?

Hello,
laravel-soap: v3.0
php: v8.1.6
laravel: v9.17.0

**Comment by CodeDredd** [comment]
Thats a hard one....
can you please compare `dump($client->debugLastSoapRequest());` in my package with `$client->__getLastRequest()` with original soap client and look what is different so i probably can fix it?
