### ISSUE TITLE
Cant install with php version 8.0

### ISSUE THREAD

**Issue by alanx15a2** [CodeDredd/laravel-soap#236]
### Steps to reproduce the behavior

Document say it support php 8.0, but when i run ```composer require codedredd/laravel-soap``` 
it show
```
  Problem 1
    - codedredd/laravel-soap v3.0.0.beta.0 requires php-soap/psr18-wsse-middleware ^1.1 -> satisfiable by php-soap/psr18-wsse-middleware[v1.1.0].
    - codedredd/laravel-soap[v3.0.0.beta.1, ..., v3.0.1] require veewee/xml ^1.3 -> satisfiable by veewee/xml[v1.3.0, v1.4.0, 1.5.0, 1.6.0].
    - php-soap/psr18-wsse-middleware v1.1.0 requires veewee/xml ^1.0 -> satisfiable by veewee/xml[v1.0.0, ..., 1.6.0].
    - veewee/xml[v1.0.0, ..., v1.0.1] require azjezz/psl ^1.6 -> satisfiable by azjezz/psl[1.6.0, ..., 1.9.x-dev].
    - veewee/xml[v1.1.0, ..., 1.6.0] require azjezz/psl ^1.9 || ^2.0 -> satisfiable by azjezz/psl[1.9.0, ..., 1.9.x-dev, 2.0.0-rc1, ..., 2.1.x-dev].
    - azjezz/psl[1.6.0, ..., 1.9.x-dev] require ext-sodium * -> it is missing from your system. Install or enable PHP's sodium extension.
    - azjezz/psl[2.0.0-rc1, ..., 2.1.x-dev] require php ~8.1.0 -> your php version (8.0.13) does not satisfy that requirement.
    - Root composer.json requires codedredd/laravel-soap ^3.0 -> satisfiable by codedredd/laravel-soap[v3.0.0.beta.0, ..., v3.0.1].
```

### Expected behavior

Install successfully.

### Actual behavior

Install error.

### Additional information

php 8.0.13
windows 11
wamp

Please tell if you need any other detail information.
Thank you!

**Comment by CodeDredd** [comment]
arrrgghhh....the unit tests were running with 8.0.20...but it seems another package is causing the problem

**Comment by alanx15a2** [comment]
Ohh... , I forgot to enable sodium extention.
When I enable the extention, it can install without any error!
Dont know why it show ```azjezz/psl[2.0.0-rc1, ..., 2.1.x-dev] require php ~8.1.0 -> your php version (8.0.13) does not satisfy that requirement.``` when I didnt enable the extention haha..
