### ISSUE TITLE
Error sending arguments

### ISSUE THREAD

**Issue by ElRochito** [CodeDredd/laravel-soap#237]
HI,

Since I've upgrade to 3.0.1, I've got problem while sending arguments.

Indeed, for example : 
```
Soap::baseWsdl($request->host)
       ->withOptions([
            'soap_version' => SOAP_1_2,
        ])
        ->call('GetTeeSheetByDate', [
                'courseId' => 1,
                'fromDateOA' => '444444',
                'toDateOA' => '444444'
            ]);
```

It generate a request like this  (on version 3.0.1)
```
<?xml version="1.0" encoding="UTF-8"?>\n
    <env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:ns1="http://tempuri.org/Psk.WTS8.WebServices/OnlineReservationService"><env:Body><ns1:GetTeeSheetByDate/><param1>44444</param1><param2>44444</param2></env:Body></env:Envelope>\n
```

We should have : (on version 3.0.0.beta.3 it was this good format)
```
<?xml version="1.0" encoding="UTF-8"?>\n
    <env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:ns1="http://tempuri.org/Psk.WTS8.WebServices/OnlineReservationService"><env:Body><ns1:GetTeeSheetByDate/><ns1:courseId>1</ns1:courseId><ns1:fromDateOA>44444</ns1:fromDateOA><ns1:toDateOA>44444</ns1:toDateOA></env:Body></env:Envelope>
```

Data are not correctly formatted and it missing one of them (eg: courseId)

My problem seems to be linked to your fix (fix(#233): Array of arguments is not working correctly @CodeDredd (https://github.com/CodeDredd/laravel-soap/commit/04113b49992370f495db821ec3c7434eee6ca8eb))

My WSDL looks like : 
<img width="684" alt="image" src="https://user-images.githubusercontent.com/1737307/180202562-9d104c54-db1b-496f-a3c5-7912cbf1aea6.png">

**Comment by CodeDredd** [comment]
Thanks for reporting. As soon i find time i try to fix it....can you please try out version 3.0.0, so i know that my fix is causing the error ?

**Comment by ElRochito** [comment]
On v3.0.0.beta.3 it's works fine yed

**Comment by Jaspur** [comment]
@CodeDredd could you please make fix this?
