### ISSUE TITLE
ConnectionFailed::__construct(): Argument #1 ($request) must be of type CodeDredd\Soap\Client\Request,

### ISSUE THREAD

**Issue by usyeimar** [CodeDredd/laravel-soap#263]
Good evening
Can you please help me with an error that I get when using the library, I don't know if I'm making a mistake in the configuration of this

## i am getting this error
![imagen](https://user-images.githubusercontent.com/71295346/209405527-6a40efcf-cfea-4891-a1f6-340e95cb9e68.png)

### This is my base configuration
```php
 $soap = Soap::baseWsdl('https://miportafoliouat.transunion.co/ws/UbicaPlusWebService/services/UbicaPlus')
            ->withOptions(['cache_wsdl' => WSDL_CACHE_NONE,
                'trace' => 1,
                'stream_context' => stream_context_create([
                    'ssl' => [
                        'verify_peer' => false,
                        'verify_peer_name' => false,
                        'allow_self_signed' => false
                    ],
                    'http' => [
                        'header' => 'Authorization: Basic ' . base64_encode('xxx' . ':' . 'xxx')
                    ]])
            ])->withWsse([
                'userTokenName' => '331487',
                'userTokenPassword' => '2op.bPgtinma',
                'privateKeyFile' => Storage::disk('local')->path('cifin-private.key'),
                'publicKeyFile' => Storage::disk('local')->path('cifin-public.key'),
                'serverCertificateFile' => Storage::disk('local')->path('cifin-public.key'),
                'serverCertificateHasSubjectKeyIdentifier' => true,
                'userTokenDigest' => true,
                'digitalSignMethod' => XMLSecurityKey::RSA_SHA256,
                'timestamp' => 10000,
                'signAllHeaders' => true,


            ]);
```

I would really appreciate if you help me to solve this problem

**Comment by alfonsodou** [comment]
I have the same problem. This is my code:

        $response = Soap::baseWsdl($this->wsdl)
            ->withOptions([
                'cache_wsdl' => WSDL_CACHE_NONE,
                'trace' => 1,
                'stream_context' => stream_context_create([
                    'ssl' => [
                        'verify_peer' => false,
                        'verify_peer_name' => false,
                        'allow_self_signed' => false
                    ]])
            ])->withWsse([
                'privateKeyFile' => $this->privKey,
                'publicKeyFile' => $this->publicKey,
                'digitalSignMethod' => 'RSA-SHA1',
                'signAllHeaders' => true,
            ])->call('xxxxxxxxx', $params);

Any help?
Thanks.

**Comment by alfonsodou** [comment]
> I have the same problem. This is my code:
> 
> ```
>     $response = Soap::baseWsdl($this->wsdl)
>         ->withOptions([
>             'cache_wsdl' => WSDL_CACHE_NONE,
>             'trace' => 1,
>             'stream_context' => stream_context_create([
>                 'ssl' => [
>                     'verify_peer' => false,
>                     'verify_peer_name' => false,
>                     'allow_self_signed' => false
>                 ]])
>         ])->withWsse([
>             'privateKeyFile' => $this->privKey,
>             'publicKeyFile' => $this->publicKey,
>             'digitalSignMethod' => 'RSA-SHA1',
>             'signAllHeaders' => true,
>         ])->call('xxxxxxxxx', $params);
> ```
> 
> Any help? Thanks.

Finally, it worked for me.
This is my code:

        $response = Soap::baseWsdl($this->wsdl)
            ->withOptions([
            'cache_wsdl' => WSDL_CACHE_NONE,
            'trace' => true,
            ])
            ->withWsse([
                'privateKeyFile' => $this->privKey,
                'publicKeyFile' => $this->publicKey,
            ])
            ->call('xxxxxxx', $params);

The URL for baseWsdl have this format 'https://xxxxxx?wsdl'

**Comment by usyeimar** [comment]
Thank you, I already solved the problem that I had
