### ISSUE TITLE
Error passing a date parameter

### ISSUE THREAD

**Issue by alfonsodou** [CodeDredd/laravel-soap#267]
Hello,
parameters of type date do not work correctly, they are passed empty. 
I've tried changing the 'wrap_arguments_in_array' parameter but it doesn't work anyway.

For example:

         <xsd:element maxOccurs="1" minOccurs="1" name="fecha_denuncia" type="xsd:date">
            <xsd:annotation>
               <xsd:documentation>Fecha en la cual se desea conocer la
						validez del cinemometro. Ej: 2013-10-31</xsd:documentation>
            </xsd:annotation>
         </xsd:element>

Any other parameters work correctly, but those defined as 'xsd:date' do not.

This is my code:

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->wsdl = config('soap.DGT.base_uri');
        $this->privKey = config('soap.DGT.private_key');
        $this->publicKey = config('soap.DGT.public_key');
        $this->clientSOAP = Soap::baseWsdl($this->wsdl)
                                ->withOptions([
                                    'cache_wsdl' => WSDL_CACHE_NONE,
                                    'trace' => true,
                                ])
                                ->withWsse([
                                    'privateKeyFile' => $this->privKey,
                                    'publicKeyFile' => $this->publicKey,
                                ]);
    }

    /**
     * Retorna si existe el cinemometro
     * @return Illuminate\Http\Response
     */
    public function esValidoCertificadoCinemometro($cin_id, $fecha_denuncia)
    {
        $response = $this->clientSOAP->call('esValidoCertificadoCinemometro', ['cin_id' => $cin_id,
                                                                                'fecha_denuncia' => $fecha_denuncia,]);
        if ($response->successful()) {
            return $this->successResponse($response->json());
        }

        return $this->clientSOAP->debugLastSoapRequest();
    }

And this is the output of debugLastSoapRequest():

{
    "request": {
        "headers": "",
        "body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:ns1=\"http://servappl.trafico.es/ServicioWebDGT/services/ServicioWeb\"><SOAP-ENV:Body><ns1:esValidoCertificadoCinemometro><esValidoCertificadoCinemometroPeticion><cin_id>100067</cin_id><fecha_denuncia/></esValidoCertificadoCinemometroPeticion></ns1:esValidoCertificadoCinemometro></SOAP-ENV:Body></SOAP-ENV:Envelope>\n"
    },
    "response": {
        "headers": "",
        "body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<soapenv:Envelope xmlns:dpconfig=\"http://www.datapower.com/param/config\" xmlns:dgt=\"http://www.datapower.com/extensions/functions\" xmlns:date=\"http://exslt.org/dates-and-times\" xmlns:str=\"http://exslt.org/strings\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\"><soapenv:Header/><soapenv:Body><soapenv:Fault><faultcode>soapenv:Schema.Error</faultcode><faultstring>Error de validacion de esquema : cvc-simple-type 1: element fecha_denuncia of type {http://www.w3.org/2001/XMLSchema}date may not be empty</faultstring><detail/></soapenv:Fault></soapenv:Body></soapenv:Envelope>"
    }
}

**Comment by nromero125** [comment]
I'm having the same issue. Have you found a solution?

**Comment by alfonsodou** [comment]
> I'm having the same issue. Have you found a solution?

Yes, but I didn't use CodeDredd/laravel-Soap. I wasn't able to get it to work.
I used RobRichards\WsePhp\WSSESoap ([https://github.com/robrichards/wse-php](https://github.com/robrichards/wse-php)) and RobRichards\XMLSecLibs\XMLSecurityKey to add WSSE. Finally GuzzleHttp\Client to send the Soap request. I have to build the XML with the request.
This is the code:

namespace App\Http\Controllers;

use App\Traits\ApiResponser;
use Illuminate\Http\Response;
use Illuminate\Http\Request;
use GuzzleHttp\Client;
use RobRichards\WsePhp\WSSESoap;
use RobRichards\XMLSecLibs\XMLSecurityKey;

class DGTController extends Controller
{
    use ApiResponser;

    private $privKey;
    private $publicKey;
    private $client;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->privKey = config('soap.DGT.private_key');
        $this->publicKey = config('soap.DGT.public_key');
        $this->client = new Client();
    }
    /**
     * Retorna si existe el cinemometro
     * @return Illuminate\Http\Response
     */
    public function esValidoCertificadoCinemometro(Request $request)
    {
        $input = $request->all();
        $doc = new \DOMDocument('1.0');
		
		$xml = "<soapenv:Envelope xmlns:soapenv='http://schemas.xmlsoap.org/soap/envelope/' xmlns:ser='http://servappl.trafico.es/ServicioWebDGT/services/ServicioWeb'>
        <soapenv:Header/>
        <soapenv:Body>
           <ser:esValidoCertificadoCinemometro>
              <esValidoCertificadoCinemometroPeticion>";
		
		if (isset($input['cin_id'])) {
			$xml .= "<cin_id>" . $input['cin_id'] . "</cin_id>";
		}
                 
		if (isset($input['fecha_denuncia'])) {
			$xml .= "<fecha_denuncia>" . $input['fecha_denuncia'] . "</fecha_denuncia>";
		}
                 
        $xml .= "</esValidoCertificadoCinemometroPeticion>
           </ser:esValidoCertificadoCinemometro>
        </soapenv:Body>
        </soapenv:Envelope>";
		
		$doc->loadXML($xml);

        $soap = new WSSESoap($doc);

        $soap->addTimestamp();

        /* create new XMLSec Key using AES256_CBC and type is private key */
        $objKey = new XMLSecurityKey(XMLSecurityKey::RSA_SHA1, array('type' => 'private'));

        /* load the private key from file - last arg is bool if key in file (true) or is string (false) */
        $objKey->loadKey($this->privKey, true);
        
        /* Sign the message - also signs appropiate WS-Security items */
        $options = array("insertBefore" => false);
        $soap->signSoapDoc($objKey, $options);
        
        /* Add certificate (BinarySecurityToken) to the message */
        $token = $soap->addBinaryToken(file_get_contents($this->publicKey));
        
        /* Attach pointer to Signature */
        $soap->attachTokentoSig($token);
        
        $soap_request = $soap->saveXML();
        try { 
            $response = $this->client->post('https://preapl-p3.trafico.es:8081/WS_Psancionador/services/ServicioWeb', [
                'headers' => [
                    'Content-Type' => 'application/soap+xml; charset=utf-8',
                    'SOAPAction' => 'http://www.trafico.es/servicios/psmg/psws/servicio/esValidoCertificadoCinemometro',
                ],
                'body' => $soap_request,
            ]);
        } catch (\GuzzleHttp\Exception\BadResponseException $e) {
            $response = $e->getResponse();
            return $response->getBody(); 
        }

        if ($response->getStatusCode() === Response::HTTP_OK) {
            return $response->getBody();
        }

        return $this->errorResponse("Error en la llamada al servicio", $response->getStatusCode());
    }
}



I hope it helps.
Regards.
