### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by abdulwahid** [CodeDredd/laravel-soap#274]
_PHP: 8.1
Laravel: 9.47
codedredd/laravel-soap: 3.0.2_

Hi @CodeDredd 

**Thanks for the awesome Package.**

I'm facing issue while using this Package to make API calls. I get 400 Bad request response.

Looks like it doesn't reach to the point where it generates the request body.
I followed the function calls from Package classes:
In our ApiClient class, we're calling the `call` method of package's `SoapClient` class. In the `call` method, it calls its class member method `refreshEngine`, which calls `setTransport` method. Eventually it reaches the `AbusedClient` class's constructor, from where when it calls:

```
parent::__construct($wsdl, $options);
```

it returns the error response:

![image](https://user-images.githubusercontent.com/4362643/220441392-e2d9c078-11b4-4947-a7aa-a2b2cf5eeba6.png)

Here is my code:

```
`$client = Soap::baseWsdl(config('services.api.endpoint'))

                ->withWsse([
                    'storeId' => config('services.api.store_id'),
                    'userName' => config('services.api.username'),
                    'password' => config('services.api.password'),
                ])

                ->call('SubmitTransaction', $data);
```

I've also tried:

```

$client = Soap::baseWsdl(config('services.leads_online.endpoint'))

                ->withOptions([
                    'cache_wsdl' => WSDL_CACHE_NONE,
                    'trace' => true,
                ])

                ->withWsse([
                    'storeId' => config('services.api.store_id'),
                    'userName' => config('services.api.username'),
                    'password' => config('services.api.password'),
                ])

                ->withWsa()

                ->call('SubmitTransaction', $data);
```

The `storeId` is expected for authentication purpose, I've also tried by removing it. 
May be I'm missing something or doing something wrong somewhere. 
Can you please take a look an guide me here.
Thanks in advance :-)

**Comment by robertorinaldi-dev** [comment]
I'm getting the same error.
@abdulwahid did you solve it?

**Comment by robertorinaldi-dev** [comment]
```
$client = Soap::baseWsdl('https://www.w3schools.com/xml/tempconvert.asmx?WSDL');

$response = $client->FahrenheitToCelsius([
            'Fahrenheit' => '75',
        ]);
```

Gives the same error

**Comment by abdulwahid** [comment]
@robertorinaldi-dev Nope, I couldn't figure it out yet.

@CodeDredd Can you please take look when possible?

**Comment by nathan-io** [comment]
This is a complete guess, but I noticed that in the closed PR to upgrade to Laravel 10, there are some other potentially relevant vendor package minimum versions which are bumped:

```
"phpro/soap-client": "^v2.1.0",
"php-soap/psr18-transport": "^1.3",
"php-soap/psr18-wsse-middleware": "^2.1",
"veewee/xml": "^2.6",

"php-http/discovery": "^1.14",
"php-http/message": "^1.13",
"php-http/client-common": "^2.6",
```

Sources: 

- https://github.com/tonaflcastelan/laravel-soap/blob/7e4ab3b9e823b8f6a1dc7ad8f8cbdc5a7fe6a96c/composer.json
- https://github.com/tonaflcastelan/laravel-soap/tree/feature/laravel-10-support

---

I'm sure that many if not all of these updates were necessary solely to support of the PHP 8.1 minimum version constraint. 

However, I wonder if by updating some of these dependencies (in particular the `phpro` and `php-soap` packages) it would indirectly solve this issue. Perhaps some behavior or assumption has changed and one or more of these packages needed to be updated anyway.

One test would be to use `tonaflcastelan/laravel-soap/tree/feature/laravel-10-support` in a fresh L10 project and see if this issue persists. Or, to manually edit this package's `composer.json` in some existing Laravel 9 project.

**Comment by nathan-io** [comment]
Unfortunately, using `tonaflcastelan/laravel-soap/tree/feature/laravel-10-support` in a fresh L10 project didn't work.

It doesn't look like this package is maintained anymore, hopefully we can find another solution or just create the request manually.

**Comment by CodeDredd** [comment]
I've updated the packages. Maybe the error is gone now.
