### ISSUE TITLE
Problem with binary data

### ISSUE THREAD

**Issue by e-macs** [CodeDredd/laravel-soap#75]
I'm expexting to receive around 700KB of text data in response(binary representation of file). When I try to get body() from response I have empty string, json() gives null. What may be reason for this? some memory limits? I'm running it on artisan dev server.

**Comment by CodeDredd** [comment]
Can you give some more details? So you makeing an SOAP call to get a file right? Never testet that...i try to make a test if i can reproduce your case.
Memory limit shouldn't be the reason.
