### ISSUE TITLE
Server was unable to read request. ---> There is an error in XML document (2, 252). ---> The string '' is not a valid AllXsd value

### ISSUE THREAD

**Issue by matthaselip** [CodeDredd/laravel-soap#89]
when trying to pass in any date fields, you receive the following error:

Server was unable to read request. ---> There is an error in XML document (2, 252). ---> The string '' is not a valid AllXsd value

Ive tried almost every date format to fix this.  The field type from what the soap api docs state is datetime, however there seems to be a lot of people stating that you should use 

`->format('c')` if using Carbon

Do you know how i can get around this?

**Comment by CodeDredd** [comment]
@matthaselip sry for the late answer. Having kids leaves sometimtes no time...especally now ^^....
Can u give me a full example of your request ? Don't get what you mean exactly.

**Comment by ilkerkocatepe** [comment]
I have the same error.

**Comment by CodeDredd** [comment]
@ilkerkocatepe Do i get right, the error occurs if you pass a carbon date to soap request? It would be nice if you could post me an example request how the error happens. Thanks

**Comment by ilkerkocatepe** [comment]
Hello @CodeDredd ,
The error is about XML file. In my example, XML requires DateTime class for a parameter. I tried a lot of variations. Ever time, the error was:
`Server was unable to read request. ---> There is an error in XML document (2, 252). ---> The string '' is not a valid AllXsd value`

Only this format worked for me:
`DateTime::createFromFormat('Y-m-d\TH:i:s', date('Y-m-d\TH:i:s', strtotime(now())))`

Best regards

**Comment by CodeDredd** [comment]
@ilkerkocatepe So the problem is more with carbon to get the right format ? .... Hmmm should be doable to get the right one. But i think you wanna just pass the carbon object and i do the formatting in the client ?

**Comment by ilkerkocatepe** [comment]
@CodeDredd Actually, there is no problem with your package or Carbon :)) XML just want to DateTime class

**Comment by CodeDredd** [comment]
@ilkerkocatepe Thanks for the conclusion ^^.
