### ISSUE TITLE
Error with parameters - parameter name:s

### ISSUE THREAD

**Issue by pirex360** [CodeDredd/laravel-soap#90]
I'm using v2.x.

Returns : `String reference not set to an instance of a String.\nParameter name: s"}`

The soap method has parameters, but it just ignore my parameters.

```
$response = Soap::baseWsdl($this->baseWsdl)
                            ->withOptions($options)
                            ->call('mSocioDadosPessoais', $parameters);
 return $response->body();
```

**Comment by matthaselip** [comment]
did you create the config\soap.php config file?  im wondering if the config file super seeds withOptions

**Comment by pirex360** [comment]
Solved.... for some reason with the soap service i use, the parameters needed to be in double array 

```
$params = [ ... ];
$params = array($params);
```
